---
all:
  hosts:
    R1: { ansible_host: 172.16.1.101 }
    R2: { ansible_host: 172.16.1.102 }
    R3: { ansible_host: 172.16.1.103 }
  vars:
    ansible_user: cisco
    ansible_ssh_pass: cisco
    ansible_os: ios
