#
# Get configuration from managed hosts using "show running" command
#
---
- name:  Get device configuration
  hosts: all
  tasks:
  - name: Grab configuration
    ios_command:
      commands: show running
    register: cfg

  - name: Save configuration to local file
    copy:
      content: "{{cfg.stdout[0]}}"
      dest: "{{repository}}/{{inventory_hostname}}.cfg"
    delegate_to: localhost