#
# Get configuration from managed hosts using scp from system:running-config
#
---
- name:  Get device configuration
  hosts: all
  connection: local
  vars:
    actual_config: "{{git_repository}}/{{inventory_hostname}}.actual"
    saved_config:  "{{git_repository}}/{{inventory_hostname}}.cfg"
  tasks:
  - name: Make sure we're in the right branch
    shell: git checkout {{git_branch|default('master')}}
    args:
      chdir: "{{git_repository}}"
    run_once: true
    changed_when: no

  - set_fact:
      scp_cmd: >
        sshpass -p {{ansible_ssh_pass}}
          scp {{ansible_user}}@{{ansible_host|default(inventory_hostname)}}:system:running-config
            {{ actual_config }}

  - name: Grab configuration
    command: "{{scp_cmd}}"

  - name: Save cleaned-up configuration
    copy:
      content: "{{ lookup('file',actual_config)|clean_config(clean_patterns) }}"
      dest: "{{ saved_config }}"

  - name: Remove actual configuration file
    file: name={{actual_config}} state=absent
