---
- name: Creating build directories for each host
  hosts: localhost
  tasks:
    - name: remove host config file
      file: path={{ build_dir }} state=absent
      run_once: true
    - name: remove host config file
      file: path={{ build_dir }} state=directory
      run_once: true
      