---
- hosts: all
  name: Create node data model
  tags: [ model ]
  tasks:
  - include_vars: "{{inventory_dir}}/{{model|default('fabric.yml')}}"
    run_once: true
  - name: Create per-node data model from fabric data model
    template: src=model/fabric-to-nodes.j2 dest={{inventory_dir}}/nodes.yml
    run_once: true

- hosts: all
  name: Validate fabric connectivity
  tasks:
  - include_vars: "{{inventory_dir}}/nodes.yml"
    tags: [ config,validate ]
  - name: Configure LLDP on fabric devices
    include_tasks: "{{ansible_os}}/deploy_lldp.yml"
    tags: [ config ]
  - name: Wait for LLDP to start
    include_tasks: lldp/wait.yml
  - name: Gather LLDP facts
    include_tasks: "{{item}}"
    with_first_found:
      - "{{ansible_os}}/lldp_facts.yml"
      - "lldp/napalm_lldp_facts.yml"
    tags: [ validate ]
  - name: Validate connectivity using LLDP neighbors
    include_tasks: lldp/validate.yml
    tags: [ validate ]
