#
# Break configuration on various devices in the network
#
---
- name: Disable SNMP community
  hosts: all
  tasks:
  - ios_config:
      provider: "{{ios_provider}}"
      lines:
      - "no snmp-server community cisco"
      - "no snmp-server community myPass"
    ignore_errors: true

- name: Enable SNMP community
  hosts: E2,E4,PE1,PE2
  tasks:
  - ios_config:
      provider: "{{ios_provider}}"
      lines:
      - "snmp-server community myPass"

- name: Disable SNMP traps
  hosts: all
  tasks:
  - ios_config:
      provider: "{{ios_provider}}"
      lines:
      - "no snmp-server host 10.0.0.1 traps cisco"
    ignore_errors: true

- name: Enable SNMP traps
  hosts: E1,E2,E4,PE2
  tasks:
  - ios_config:
      provider: "{{ios_provider}}"
      lines:
      - "snmp-server host 10.0.0.1 traps cisco"

- name: Disable syslog
  hosts: all
  tasks:
  - ios_config:
      provider: "{{ios_provider}}"
      lines:
      - "no logging host 10.0.0.1"
    ignore_errors: true

- name: Enable syslog
  hosts: E3,E4,PE1,PE2
  tasks:
  - ios_config:
      provider: "{{ios_provider}}"
      lines:
      - "logging host 10.0.0.1"

