---
- name:  Check whether SNMP community is configured on devices. Report missing communities
  hosts: all
  vars:
  - results: results
  tasks:
  - ios_command: 
      commands: "show snmp community"
    register: result
  - set_fact: error_no_community=1
    when: "not('name: '~snmp_community in result.stdout[0])"
  - file: path={{results}} state=directory
    run_once: true
  - template: src=reports/missing-community.j2 dest={{results}}/errors.log
    run_once: true
