---
- name:  Check whether SNMP community is configured on devices. Report missing communities
  hosts: all
  tasks:
  - ios_command: 
      commands: "show snmp community"
    register: result
  - set_fact: error_no_community=1
    when: "not('name: '~snmp_community in result.stdout[0])"
