---
- name:  Check whether SNMP community is configured on devices. Report missing communities
  hosts: all
  vars:
  - results: "{{inventory_dir}}/results"
  tasks:
  - set_fact: report=errors.j2
    when: report is not defined
  - include: "{{item}}"
    with_fileglob: [ "tests/*.yml" ] 
  - include: "reports/{{fmt|default('template')}}.yml"
