---
- name:  Check whether SNMP community is configured on devices. Report missing communities
  hosts: all
  tasks:
  - set_fact: results={{ results|default(playbook_dir ~ '/results') }}
  - include_tasks: "{{item}}"
    with_fileglob: [ "tests/*.yml" ]
    ignore_errors: true
#  - include_tasks: "reports/{{fmt|default('template')}}.yml"
